package walter.duncan.dndwebapi.exceptions;

public enum BusinessRuleViolation {
    CHARACTER_ALIGNMENT_NOT_VALID,
    CHARACTER_ABILITY_SCORE_OUT_OF_BOUNDS,
    CHARACTER_CURRENT_HIT_POINTS_EXCEEDS_MAX_HIT_POINTS,
    CHARACTER_MAX_HIT_POINTS_LESS_THAN_CURRENT_HIT_POINTS,
    CHARACTER_TYPE_INCORRECT_COLOR_FORMAT,
    CHARACTER_CLASS_ILLEGAL_HIT_DIE,
    CHARACTER_INVENTORY_ITEM_TYPE_NOT_SUPPORTED,
    CHARACTER_INVENTORY_TOO_BIG,
    WEAPON_NORMAL_RANGE_EXCEEDS_LONG_RANGE,
    WEAPON_LONG_RANGE_LESS_THAN_NORMAL_RANGE,
}