package walter.duncan.dndwebapi.exceptions;

public enum BusinessRuleViolation {
    CHARACTER_ALIGNMENT_NOT_VALID,
    CHARACTER_ABILITY_SCORE_OUT_OF_BOUNDS,
    CHARACTER_CURRENT_HIT_POINTS_EXCEEDS_MAX_HIT_POINTS,
    CHARACTER_MAX_HIT_POINTS_LESS_THAN_CURRENT_HIT_POINTS,
    CHARACTER_TYPE_INCORRECT_COLOR_FORMAT,
    CHARACTER_CLASS_ILLEGAL_HIT_DIE,
    CHARACTER_INVENTORY_ITEM_TYPE_NOT_SUPPORTED,
    CHARACTER_INVENTORY_TOO_BIG,
    CHARACTER_PORTRAIT_ILLEGAL_FILE_TYPE,
    WEAPON_NORMAL_RANGE_EXCEEDS_LONG_RANGE,
    WEAPON_LONG_RANGE_LESS_THAN_NORMAL_RANGE,
    RESOURCE_MAY_NOT_BE_DELETED_WHEN_REFERENCED_IN_INVENTORY,
    ENCOUNTER_CHARACTER_ALREADY_PARTICIPANT,
    ENCOUNTER_CHARACTER_ALREADY_PARTICIPANT_IN_ACTIVE_ENCOUNTER,
    ENCOUNTER_JOIN_ONLY_ALLOWED_WHEN_GATHERING_PARTICIPANTS,
    ENCOUNTER_START_ONLY_ALLOWED_WHEN_GATHERING_PARTICIPANTS,
    ENCOUNTER_CLOSE_ONLY_ALLOWED_IN_PROGRESS,
    ENCOUNTER_ADVANCE_TURN_ONLY_ALLOWED_IN_PROGRESS,
    ENCOUNTER_ACTION_NOT_VALID,
    ENCOUNTER_NO_PARTICIPANTS,
    ENCOUNTER_JOIN_REQUEST_ALREADY_PENDING_FOR_CHARACTER
}